package:
  name: spline
  version: "0.10.1dev0"

source:
     - path: ../../..

build:
  number: 1
  ignore_run_exports_from:
    - nvcc_linux-64                   # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - cmake =3.23
    - ninja
    - setuptools
    - nvcc_linux-64 >=10.1             # [linux]

  host:
    - python
    - numpy {{ numpy }}
    - pybind11 >=2.8

  run:
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}

  test:
      requires:
        - pytest
      source-files:
        - python/test/test_basic.py
      commands:
        - pytest -s python/test/test_basic.py

about:
    home: https://rieslab.de
    summary: "Cubic Spline PSF Implementation"
    description: "Tbd."
